version: '3.4'

services:
  request.api:
    image: ${DOCKER_REGISTRY-}request
    build:
      context: .
      dockerfile: Services/Request.API/Dockerfile


  user.api:
    image: ${DOCKER_REGISTRY-}user
    build:
      context: .
      dockerfile: Services/User.API/Dockerfile


  service.api:
    image: ${DOCKER_REGISTRY-}service
    build:
      context: .
      dockerfile: Services/Service.API/Dockerfile


  laboratory.api:
    image: ${DOCKER_REGISTRY-}laboratory
    build:
      context: .
      dockerfile: Services/Laboratory.API/Dockerfile

  requestmanagementapigateway:
    image: ${DOCKER_REGISTRY-}requestmanagementapigateway
    build:
      context: .
      dockerfile: ApiGateways/RequestManagementAPIGateway/Dockerfile