apiVersion: v1
kind: Service
metadata:
  name: requestnodeportservice-srv
spec:
  type: NodePort
  selector:
    app: requestservice
  ports:
  - name: requestservice
    protocol: TCP
    port: 80
    targetPort: 80
